spring.application.name=expense-tracker
server.port=8080

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/expensedb
spring.datasource.username=postgres
spring.datasource.password=kb9gb11cr7

# Hibernate Configuration (hibernate.ddl-auto=create-for creating new database/table, update-for updating existing database )
spring.jpa.hibernate.ddl-auto=update .
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Configuration
# This must be a very long, complex, 256-bit string. You can generate one using a secure random generator or an online tool.
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000